export default{
    namespaced:true,
    state:{
        colors:[
            {
                name:'蓝色',
                color:'#4e7ca1',
            },
            {
                name:'黑色',
                color:'#131824',
            },
            {
                name:'灰色',
                color:'#545c64',
            },
            {
                name:'红色',
                color:'#de7897',
            },
            {
                name:'紫色',
                color:'#806d9e'
            },
            {
                name:'绿色',
                color:'#2c9678'
            }
        ],
        currentColor:{
            name:'蓝色',
            color:'#4e7ca1',
        }
    },
    getters:{
        getColorNames(state){
            return state.colors.map(r=>r.name)
        }
    },
    mutations:{
        updatedColorName(state,val){
            state.currentColor=val
        }
    },
    actions:{
        updatedColorName(store,val){
            store.commit('updatedColorName',val)
        }
    },
    module:{

    },
}